name: ci

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: run tests
        run: go test ./... -coverprofile=c.out

      - name: generate coverage html
        if: matrix.os == 'ubuntu-latest'
        run: go tool cover -html=c.out -o coverage.html

      - name: upload coverage artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: go-coverage
          path: |
            c.out
            coverage.html
          retention-days: 7
