name: golangci-lint

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
